#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "driver/adc.h"
#include "driver/can.h"
#include "driver/dac.h"
#include "driver/gpio.h"
#include "driver/i2c.h"
#include "driver/i2s.h"
#include "driver/ledc.h"
#include "driver/rmt.h"
#include "driver/mcpwm.h"
#include "driver/spi_common.h"
#include "driver/spi_master.h"
#include "driver/spi_slave.h"
#include "driver/timer.h"
#include "driver/uart.h"
#include <esp32/clk.h>

#include <esp_sleep.h>
#include <esp_wifi.h>
#include <esp_websocket_client.h>
#include <esp_event_loop.h>
#include <mqtt_client.h>
